###
GET  http://localhost:2100/api/all

###
GET  http://localhost:2100/api/teachers

###
POST  http://localhost:2100/api/register

{
"name": "asas",
"phone": "+99886987983",
"course": "ielts",
"date": "21/03/2022"
}

###
POST  http://localhost:2100/api/addTeacher
Content-Type:"application/json"

{
    "name": "John",
    "phone": "+99886987983",
    "course": "ielts",
}