GET  http://localhost:2100/api/users
Content-Type: "application/json"

###
POST  http://localhost:2100/api/register
Content-Type: "application/json"

{
"name": "asas",
"phone": "+99886987983",
"course": "ielts",
"date": "21/03/2022"
}